"""
ChunkEmbedding data model for vector search.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class ChunkEmbedding(BaseModel):
    """
    Represents a text chunk with its embedding vector for RAG retrieval.

    Stored in Qdrant vector database with 768-dimensional embeddings.

    Attributes:
        id: Unique chunk identifier (UUID)
        chapter_id: Reference to parent chapter
        chapter_number: Chapter number for filtering
        chunk_text: The actual text content of this chunk
        embedding: 768-dimensional embedding vector (generated by Gemini)
        position: Position of this chunk within the chapter (0-indexed)
        token_count: Number of tokens in chunk_text
    """

    id: str = Field(..., description="Unique chunk identifier")
    chapter_id: str = Field(..., description="Parent chapter ID")
    chapter_number: int = Field(..., ge=1, description="Chapter number")
    chunk_text: str = Field(
        ...,
        min_length=1,
        max_length=10000,
        description="Text content of the chunk"
    )
    embedding: List[float] = Field(
        ...,
        min_length=768,
        max_length=768,
        description="768-dimensional embedding vector"
    )
    position: int = Field(..., ge=0, description="Position within chapter")
    token_count: int = Field(..., ge=1, description="Number of tokens")

    class Config:
        json_schema_extra = {
            "example": {
                "id": "chunk-001-000",
                "chapter_id": "chapter-01",
                "chapter_number": 1,
                "chunk_text": "Physical AI refers to artificial intelligence systems...",
                "embedding": [0.123, -0.456, 0.789],  # Truncated for brevity
                "position": 0,
                "token_count": 512
            }
        }
